### ISSUE TITLE
Paper markup handout on 2 pages?

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/workshops#17]
Would it be possible to reduce this to 2 pages? It would save printer paper and the need to staple. I think it should still be plenty large enough text but let me know if you think that's not true.

**Comment by petermr** [comment]
Is this Q for me?

Normally we do this in groups so we only need 1 copy per table (ca 6) , but
we normally have 6 pages...

On Sun, Apr 12, 2015 at 8:54 PM, Jenny Molloy notifications@github.com
wrote:

> Would it be possible to reduce this to 2 pages? It would save printer
> paper and the need to staple. I think it should still be plenty large
> enough text but let me know if you think that's not true.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/workshops/issues/17.

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by Treblesteph** [comment]
Done - let me know if anything else needs changing.

**Comment by jcmolloy** [comment]
Thank you!
